// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CollectionViewDrawer.iOS
{
	public partial class UICollectionViewDrawerCell : UICollectionViewCell
	{

		public UICollectionViewDrawerCell (IntPtr handle) : base (handle) { }


		public void SetData (string text) => label.Text = text;
	}
}
